### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by WenXin20** [CGessinger/Nekos-Enchanted-Books#1]
`Minecraft v1.16.5`
`Forge v36.0.7`
`NEB v1.0.0`

My server crashed when trying to run this mod.
[Crash Report](https://gist.github.com/WenXin20/ef5e4e5608eba355fbfa0dc9a1f57056#file-neko-s_enchanted_books_crash-txt-L36)

**Comment by CGessinger** [comment]
Hello,
thank you for reaching out. Please note that this mod is client side only! So no need to run it on your server, only use it on your local Minecraft machine. Therefore you can join every server when using this mod (even vanilla ones)

**Comment by WenXin20** [comment]
Ah, thanks. I wasn't aware of that.

**Comment by BBoldt** [comment]
Could you mark it as a client only mod so forge will just disable it if it gets placed on a server?

I'm not a modder but I know there is a way to do it, maybe this? https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

**Comment by Gbergz** [comment]
> Could you mark it as a client only mod so forge will just disable it if it gets placed on a server?
> 
> I'm not a modder but I know there is a way to do it, maybe this? https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

**+** 1 on this suggestion. Mod crashes on server. But if it is missing the server will be marked as an Incompatible FML Modded Server.
![image](https://user-images.githubusercontent.com/26634554/119145136-a6474680-ba49-11eb-9c0a-6e3b9c4cb528.png)

**-** Gbergz

**Comment by Gbergz** [comment]
As stated above, would be absolutely lovely if it worked on servers even though I understand it'd a client side mod and it isn't meant to work on servers. 
Along with marking it as client side only so the "Incompatible FML modded server" message is gone.

Thanks for reading, again.
**-** Gbergz
