### ISSUE TITLE
Not marked as a client-mod with forge.

### ISSUE THREAD

**Issue by iMahco** [CGessinger/Nekos-Enchanted-Books#4]
Low priority issue!

You can make a mod mark itself as client-only in order to remove the red X that appears on peoples screens when loading up multi-player server list.
Would appreciate if that was implemented!

Starting up a server with some friends and wanted to throw this into the pack but previous worlds has shown me that having to let everyone know the X can be ignored always draws concern, especially if their computer or connection just can't manage to join the world; that x is always the go-to blame, gets annoying letting them know the world is _fine_ and its just their pc's lol.

Thanks in advance!! <3 Really love the book art!!

**Comment by iMahco** [comment]
Tossing this in here in hopes it helps!
[https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods](url)

**Comment by nekomaster1000** [comment]
This has been done in Release 1.3! Thanks for bringing it up + the kind words! <3
